apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-be
  namespace: flux-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bw-be
  template:
    metadata:
      labels:
        app: bw-be
    spec:
      containers:
        - name: bw-be
          image: jeanmichelbb/bw-be:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_NAME
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bw-fe
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bw-fe
  template:
    metadata:
      labels:
        app: bw-fe
    spec:
      containers:
        - name: bw-fe
          image: jeanmichelbb/bw-fe:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_API_URL
            - name: VITE_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_GOOGLE_CLIENT_ID
            - name: VITE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_API_KEY
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"