apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bw-fe
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bw-fe
  policy:
    semver:
      range: "*"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bw-be
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bw-be
  policy:
    semver:
      range: "*"