apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: botwhy
type: Opaque
data:
  DB_USER: YXBw
  DB_PASSWORD: YXBw
  DB_HOST: bXlzcWw=
  DB_NAME: Y2hhdGJveF9kYg==
  SECRET_KEY: S3NucmprZmt3ZWZtS2xta3dlamZud2Vm
  OPENAI_API_KEY: c2stcHJvai02aGx0RFlJemhMTHplaXpnTjNOMzhqQUR5R1V3RmZHbDNfYlhXQWlhcHJhaXZsMGtUSlRwSGx2cy1FdGU2cTdISnlVN0tCRnRZZ1QzQmxia0ZKS3doTHd3R0puc0szMU41MHhsS1pLb3JPYjl2MHpubDNPaUM1T1pzVFZaaFIzOTJGbm9uMlNQR1BvbXRtWmh5bmUzei1MV0xWRUE=
  GOOGLE_CLIENT_ID: MTA0NzA2MTM1Njg2OC10M29pMjRkMWNraXQ1MWM3ZG5lNDFpNGZvZGZ1OXAxdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  VITE_API_KEY: S3NucmprZmt3ZWZtS2xta3dlamZud2Vm
  VITE_API_URL: aHR0cHM6Ly9ib3R3aHlhcGkuc2FjZW5wYXBpZXIub3Jn
  VITE_GOOGLE_CLIENT_ID: MTA0NzA2MTM1Njg2OC10M29pMjRkMWNraXQ1MWM3ZG5lNDFpNGZvZGZ1OXAxdi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  GOOGLE_CLIENT_SECRET: R09DU1BYLU1JSVlVVThFWUtFY2xRemM3czFDM2tQVHk5SV8=