version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - backend
    environment:
      - API_KEY=${OPENAI_API_KEY}

  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_HOST=${DB_HOST}  
      - DB_NAME=${DB_NAME}  
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
      - SECRET_KEY=${SECRET_KEY}  
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}  
      MYSQL_USER: ${DB_USER}  
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: