apiVersion: apps/v1
kind: Deployment
metadata:
  name: botwhy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botwhy-backend
  template:
    metadata:
      labels:
        app: botwhy-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting for MySQL..."; sleep 3; done']
      containers:
        - name: botwhy-backend
          image: jeanmichelbb/oci-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: botwhy-backend-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: botwhy-backend
spec:
  selector:
    app: botwhy-backend
  ports:
    - port: 8000
      targetPort: 8000
