apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-botwhy
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-botwhy
  project: botwhy
  config: prd
  managedSecret:
    name: botwhy-backend-secret
    namespace: default
    type: Opaque
