apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/oci-frontend
    newTag: f34b17b03f480ae5fab43cb215c4ffacc91f1a19
    newName: jeanmichelbb/oci-frontend
  - name: jeanmichelbb/oci-backend
    newTag: 8d56ba497b661cafe95f87a96dc5d5d4a6566413
    newName: jeanmichelbb/oci-backend
