apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/oci-frontend
    newTag: b4010a0d6e73fd2cff67ce7ee43fca202de44f66
    newName: jeanmichelbb/oci-frontend
  - name: jeanmichelbb/oci-backend
    newTag: b4010a0d6e73fd2cff67ce7ee43fca202de44f66
    newName: jeanmichelbb/oci-backend
