
FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y pkg-config default-libmysqlclient-dev build-essential

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]