name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "frontend-react/**"
      - "backend-api/**"
      - ".github/workflows/docker-build.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build --platform linux/amd64 -t jeanmichelbb/bw-fe:latest ./frontend-react
          docker push jeanmichelbb/bw-fe:latest

      - name: Build and push backend image
        run: |
          docker build --platform linux/amd64 -t jeanmichelbb/bw-be:latest ./backend-api
          docker push jeanmichelbb/bw-be:latest