name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest myusername/myapp:latest
          docker push myusername/myapp:latest

      - name: Build React App
        run: |
          cd frontend-react
          npm install
          npm run build

      - name: Transfer React Build Files
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend-react/build/*"
          target: "/path/to/frontend/build"

      - name: SSH into server and run docker-compose
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/deploy
            docker-compose down
            docker-compose up -d
